[project]
name = "matmat37000-github-io"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1,<2.0.0",
    "mkdocs-macros-plugin>=1.5.0,<2.0.0",
    "mkdocs-material>=9.6.5,<10.0.0",
]
